### ISSUE TITLE
License error. To many nodes for basic license with 6 nodes k8s

### ISSUE THREAD

**Issue by tobg** [triliovault-k8s-issues/triliovault-k8s-issues#18]
## Issue Description
License error running trilio basic license on a 6 node k8s cluster.
It says 14 Nodes while I use 6. See bellow.

### Preconditions

Describing preconditions is a great source of information for troubleshooting an issue. Provide details on the Kubernetes flavour, Kubernetes version, storage used,  CSI driver version, detailed information on resources created (Target, BackupPlan, Backup, Restore, etc), and TrilioVault for Kubernetes version. Basically, please provide all relevant details that would help a developer set up the same environment as you have.

Example:

```
1. k8s flavour: bare metal
2. k8s version: 1.18.6
3. storage: AWS S3
4. CSI version: 
5. k8s TrilioVault version: 1.1.0
...
```

NAME           STATUS   MESSAGE                                                        CURRENT NODE COUNT   GRACE PERIOD END TIME   EDITION   CAPACITY   EXPIRATION TIME
tobg-license   Error    Cluster with capacity 14 nodes crossed max capacity 10 nodes   14                                           Basic     10         2021-09-28T00:00:00Z
➜  trilio git:(master) ✗ k get node
NAME        STATUS   ROLES    AGE    VERSION
k8smaster   Ready    master   139d   v1.18.6
k8w1        Ready    <none>   139d   v1.18.6
k8w2        Ready    <none>   139d   v1.18.6
k8w3        Ready    <none>   139d   v1.18.6
k8w4        Ready    <none>   139d   v1.18.6
k8w5        Ready    <none>   78d    v1.18.6

**Comment by prafull11** [comment]
@tobg Thanks for raising the issue. We calculate the number of nodes based on the CPU allocated to each node. TrilioVault for Kubernetes is licensed by the number of Kubernetes Worker Nodes. Each worker node license is defined as 2 CPUs. If you have  4 CPUs in a node, our license engine count that as 2 nodes. 

For more information on our licensing, please refer our licensing documentation [here](https://docs.trilio.io/kubernetes/overview/licensing)

**Comment by madhurnawandar** [comment]
Hi @tobg, let us know if that satisfies your query?

**Comment by tobg** [comment]
Hi, sorry for my late response. Yes this answer satisfies me. Thank you.
