### ISSUE TITLE
admission webhook "tvk-validation.trilio.io" denied the request: target not in Available state

### ISSUE THREAD

**Issue by colin-mccarthy** [triliovault-k8s-issues/triliovault-k8s-issues#20]
## Issue Description

Getting an error when I apply backup plan.

Error from server (target not in Available state): error when creating "backup-plan.yaml": admission webhook "tvk-validation.trilio.io" denied the request: target not in Available state

### Preconditions

```
1. k8s flavour: OpenShift 4.5.9
2. k8s version: (v1.18.3+6c42de8)
3. storage: AWS S3
4. CSI version: 
5. k8s TrilioVault version: v1.1.1
...
```

### Steps to reproduce

This part of the bug report is the most important, as developers will use this information to reproduce the issue. Issues are more likely to be fixed if it can be reproduced.

Precisely describe each step you have taken to reproduce the issue. Try to include as much information as possible, sometimes even minor differences can be crucial.

Example:

```
1. Followed Helm install docs from this page.

https://docs.trilio.io/kubernetes/overview/getting-started

```

### Actual and Expected result

To make sure that everybody involved in resolving the issue are on the same page, precisely describe the result you expected and the actual result you observed after performing the steps.

Example:

```
Expected result:

Backup snapshot to S3

Actual result:

oc apply -f backup-plan.yaml -n Colin

Error from server (target not in Available state): error when creating "backup-plan.yaml": admission webhook "tvk-validation.trilio.io" denied the request: target not in Available state

```

### Support Log Bundle

[triliovault-23-10-2020-12-02-18.zip](https://github.com/triliovault-k8s-issues/triliovault-k8s-issues/files/5430638/triliovault-23-10-2020-12-02-18.zip)

**Comment by trilio-ravitripathi** [comment]
Hi Colin,

While creating the target, Is the S3 user you have used is from **AmazonS3FullAccess** group? Can you please confirm?
If not then can you ensure that user belongs to that group and try it again?
Let me know, thanks

**Comment by madhurtrilio** [comment]
Hi @colin-mccarthy 
Thanks for reporting the issue.
Looking at the log bundle, I can see that the operator installation you did was a namespace scope installation, but the Trilio CRD's that are installed are Cluster scoped. This can happen if someone installs first a Cluster scoped Operator and then uninstalls it and recreate the operator in Namespace scope.
Openshift OLM do not delete the CRD's already present on the cluster and that is the reason for the problem.

I would recommend the following steps to fix this problem:
Step 1: Uninstall the operator
Step 2: Delete the target resource and any other Trilio resource that you created
Step 3: Delete all Trilio CRD using 
`kubectl delete crds $(kubectl get crds | grep trilio | awk '{print $1}')`
Step 4: Reinstall the operator and continue with the steps given at https://docs.trilio.io/kubernetes/overview/getting-started#create-a-target

**Comment by colin-mccarthy** [comment]
I have tried both of the requests and still get the same error.

```
Error from server (target not in Available state): error when creating "backup-plan.yaml": admission webhook "tvk-validation.trilio.io" denied the request: target not in Available state
```

I spun up an entirely new OCP cluster and new helm app. 

I verified my user from the target is in a group with AmazonS3FullAccess.


[triliovault-23-10-2020-23-38-41.zip](https://github.com/triliovault-k8s-issues/triliovault-k8s-issues/files/5432379/triliovault-23-10-2020-23-38-41.zip)

**Comment by madhurtrilio** [comment]
Hi @colin-mccarthy on further debugging we found that Redhat introduced a new way of operator packaging and auto migrated our operator. In that process they migrated our operator in an incorrect way, leading to clubbing of namespace scope operator with cluster scope CRD's. We are following up with them for this. 
While we do that you can still use the cluster channel to use a cluster scoped operator. We validated that it's been migrated correctly. 
For non openshift environment, you can also use our upstream operator. This will work for both namespace and cluster scope https://docs.trilio.io/kubernetes/use-triliovault/installing-triliovault#installing-triliovault-on-kubernetes
Note: If you plan to use the same cluster for cluster scope, you will have to follow the cleanup steps mentioned in my previous comment https://github.com/triliovault-k8s-issues/triliovault-k8s-issues/issues/20#issuecomment-715512311
