### ISSUE TITLE
no matches for kind "License" error during apply

### ISSUE THREAD

**Issue by vprocopan** [triliovault-k8s-issues/triliovault-k8s-issues#28]
kubectl apply -f license.yaml
error: unable to recognize "license.yaml": no matches for kind "License" in version "triliovault.trilio.io/v1"
what could be the problem?

**Comment by abhisek-dwivedi** [comment]
Your cluster is missing license CRD. Run the following command to confirm this.

```
kubectl get crd | grep "license"
licenses.triliovault.trilio.io                   2021-06-15T10:45:34Z
```

**Comment by vprocopan** [comment]
Thanks! it is blank, how do I run it? I installed Trilio via cluster explorer, apps.

**Comment by vprocopan** [comment]
ok i have the error 
W0621 12:21:11.867496 23 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition

**Comment by abhisek-dwivedi** [comment]
Can you please provide the output for the following commands?

1. kubectl get crd | grep "trilio"
2. kubectl get pod -n <namespace>  -> namespace where installation is done
3. helm ls -n <namespace>  -> same above namespace
4. kubectl get triliovaultmanagers -A

**Comment by vprocopan** [comment]
[vprocopan@dsisas-ctnode1 ~]$ kubectl get crd | grep "trilio"
triliovaultmanagers.triliovault.trilio.io             2021-06-21T12:20:49Z
[vprocopan@dsisas-ctnode1 ~]$ kubectl get pod -n default
NAME                                       READY   STATUS    RESTARTS   AGE
edoc-test-7c65d848db-5qrr5                 1/1     Running   0          7d16h
edoc-test-7c65d848db-mjpjn                 1/1     Running   0          7d16h
edoc-test-7c65d848db-s8kdr                 1/1     Running   0          7d16h
k8s-triliovault-operator-56496fb56-nqkwm   1/1     Running   0          16h
[vprocopan@dsisas-ctnode1 ~]$ helm ls -n default
-bash: helm: command not found
[vprocopan@dsisas-ctnode1 ~]$ kubectl helm ls -n default
Error: unknown command "helm" for "kubectl"
Run 'kubectl --help' for usage.
[vprocopan@dsisas-ctnode1 ~]$ kubectl get triliovaultmanagers -A 
No resources found
[vprocopan@dsisas-ctnode1 ~]$ kubectl get triliovaultmanagers -A
No resources found
[vprocopan@dsisas-ctnode1 ~]$

**Comment by abhisek-dwivedi** [comment]
Thanks for the info.

From the output you provided, I can see that you have only installed the operator but not installed the TVK application.
License CRD is part of TVK application. So you have to create a TVM CR and then the operator will install the TVK application
for you.

Sample TVM CR looks like this:

```
apiVersion: triliovault.trilio.io/v1
kind: TrilioVaultManager
metadata:
  name: tvk
spec:
  trilioVaultAppVersion: latest
  applicationScope: Namespaced
```

After creating the above CR you will see multiple TVK pods getting created and also you can verify that license CRD is present.
Once all pods come in running state you are good to create your license and perform backup and restore.

**Comment by vprocopan** [comment]
Thanks! Unfortunately some containers crash

![trilio](https://user-images.githubusercontent.com/6999055/122870993-0fff8c80-d337-11eb-919b-0baa4d660085.png)

**Comment by abhisek-dwivedi** [comment]
Can you provide the logs of any of the failed pod ?
```
kubectl get pod -n <namespace>
Kubectl logs -f <pod-name> -n <namespace>
````

**Comment by vprocopan** [comment]
_output of 3 failed pods:_
[vprocopan@dsisas-ctnode1 ~]$ kubectl logs -f k8s-triliovault-admission-webhook-5794cdc799-6kg66 -n default
Error from server (BadRequest): container "triliovault-admission-webhook" in pod "k8s-triliovault-admission-webhook-5794cdc799-6kg66" is waiting to start: PodInitializing
[vprocopan@dsisas-ctnode1 ~]$ kubectl logs -f k8s-triliovault-control-plane-7ff97894dd-2cqpd -n default
error: a container name must be specified for pod k8s-triliovault-control-plane-7ff97894dd-2cqpd, choose one of: [triliovault-control-plane triliovault-analyzer]
[vprocopan@dsisas-ctnode1 ~]$ kubectl logs -f k8s-triliovault-web-backend-7b956c469-tn5n8 -n default
{"component":"Manager","file":"internal/helpers/olm.go:16","func":"github.com/trilioData/k8s-triliovault/internal/helpers.SetAppScopeIfNotPresent","level":"info","msg":"Setting up the APP_SCOPE environment","time":"2021-06-22T06:07:50Z"}
2021-06-22T06:07:51.703Z        INFO    controller-runtime.metrics      metrics server is starting to listen    {"addr": ":8080"}
I0622 06:07:52.849219       1 request.go:655] Throttling request took 1.047363029s, request: GET:https://10.43.0.1:443/apis/extensions/v1beta1?timeout=32s
2021-06-22T06:07:54.002Z        ERROR   setup   Unable to setup indexes {"error": "no matches for kind \"BackupPlan\" in version \"triliovault.trilio.io/v1\""}
runtime.main
        GOROOT/src/runtime/proc.go:204

**Comment by abhisek-dwivedi** [comment]
Thanks. I think still the CRDs are not installed properly.

`kubectl get crd | grep "trilio"`

Also, can you provide logs of the operator pod?

`kubectl logs -f k8s-triliovault-operator-56496fb56-nqkwm`

Which k8s version are you using?

**Comment by abhisek-dwivedi** [comment]
I think I understood the issue. There is some version compatibility issue here.
Just delete the TVM CR you created earlier and wait for all the pods to get deleted successfully.

Use this TVM CR:

```
apiVersion: triliovault.trilio.io/v1
kind: TrilioVaultManager
metadata:
  name: tvk
spec:
  trilioVaultAppVersion: v2.0.2
  applicationScope: Namespaced
```

Recreate with above TVM CR.

**Comment by vprocopan** [comment]
I deleted the crd, when i recreate i get 
[vprocopan@dsisas-ctnode1 ~]$ kubectl create -f triliovault-manager.yaml
Error from server (NotFound): error when creating "triliovault-manager.yaml": the server could not find the requested resource (post triliovaultmanagers.triliovault.trilio.io)
What did I do wrong?

**Comment by abhisek-dwivedi** [comment]
You deleted the operator CRD which is used by Operator to install the TVK application. You have to delete and re-install the operator.

**Comment by vprocopan** [comment]
After everything installed and running + license, I get 
![image](https://user-images.githubusercontent.com/6999055/122885071-67a5f400-d347-11eb-9a8f-28fcc30f25c6.png)
in the application itself

**Comment by abhisek-dwivedi** [comment]
Refer to the steps mentioned in the [docs](https://docs.trilio.io/kubernetes/management-console/user-interface/accessing-the-ui#step-2-assign-fqdn-for-tvk-ui) to access the UI:

I think you are using nodePort to access the UI. So make an /etc/host entry with ingress host and node IP.

**Comment by vprocopan** [comment]
![image](https://user-images.githubusercontent.com/6999055/122892871-75ab4300-d34e-11eb-8bcd-e79a636eedd2.png)

**Comment by vprocopan** [comment]
i think i did it, thank you very much for assisting me.

**Comment by madhurtrilio** [comment]
hi @vprocopan thanks for your support in helping us resolve your issue. Can we mark this ticket as closed?

**Comment by vprocopan** [comment]
Sure, we can make it closed. Thank you again for brief support!

Respectfully yours, Vitalie Procopan. skype: spiker1988

вт, 22 июн. 2021 г., 17:46 madhurtrilio ***@***.***>:
