### ISSUE TITLE
Where define volumeSnapshotClass to use

### ISSUE THREAD

**Issue by Grounz** [triliovault-k8s-issues/triliovault-k8s-issues#31]
## volumeSnapshotClass

Hi on all documentation i don't find where i can config volumeSnapshotClass use for trilio snapshot ?

**Comment by prafull11** [comment]
Hello @Grounz 

Thank you for raising the issue. TVK picks up the `storageClass` from the PV it is backing up.  Let's say I have created a backup for the which is backing up a PV with storageClass `csi-gce-pd`. 

```
% kubectl get storageclasses.storage.k8s.io 
NAME                 PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
csi-gce-pd           pd.csi.storage.gke.io   Delete          WaitForFirstConsumer   false                  29h
```

TVK will use`pd.csi.storage.gke.io` provisioner from the SC and find the VolumeSnapshotClass whose driver matches this provisioner and uses this `volumesnapshotclass` in the backup.
```
% kubectl get volumesnapshotclasses.snapshot.storage.k8s.io  
NAME                     DRIVER                  DELETIONPOLICY   AGE
default-snapshot-class   pd.csi.storage.gke.io   Delete           29h
```
If it finds the multiple `volumesnapshotclass` with the same driver as of the StorageClass provisioner, we pick the volumesnapshotclass with the default annotations `snapshot.storage.kubernetes.io/is-default-class: true` set.

I hope you find this information useful. Please let me know if you need any more information.

**Comment by madhurtrilio** [comment]
Hello @Grounz , hope the explaination from @prafull11 was helpful. Closing this ticket due to inactivity
